import {IQuranChapters} from '../types';

const QuranChapters: IQuranChapters[] = [
  {
    code_v1: 93,
    firstPage: 1,
    hasBasmalah: false,
    id: 1,
    lastPage: 1,
    revelationPlace: 'makkah',
    slug: 'al-fatihah',
    translatedName: 'الفاتحة',
    transliteratedName: 'الفاتحة',
    type: 'chapter',
    versesCount: 7,
  },
  {
    code_v1: 94,
    firstPage: 2,
    id: 2,
    lastPage: 49,
    revelationPlace: 'madinah',
    slug: 'al-baqarah',
    translatedName: 'البقرة',
    transliteratedName: 'البقرة',
    type: 'chapter',
    versesCount: 286,
  },
  {
    code_v1: 95,
    firstPage: 50,
    id: 3,
    lastPage: 76,
    revelationPlace: 'madinah',
    slug: 'ali-imran',
    translatedName: 'آل عمران',
    transliteratedName: 'آل عمران',
    type: 'chapter',
    versesCount: 200,
  },
  {
    code_v1: 96,
    firstPage: 77,
    id: 4,
    lastPage: 106,
    revelationPlace: 'madinah',
    slug: 'an-nisa',
    translatedName: 'النساء',
    transliteratedName: 'النساء',
    type: 'chapter',
    versesCount: 176,
  },
  {
    code_v1: 97,
    firstPage: 106,
    id: 5,
    lastPage: 127,
    revelationPlace: 'madinah',
    slug: 'al-maidah',
    translatedName: 'المائدة',
    transliteratedName: 'المائدة',
    type: 'chapter',
    versesCount: 120,
  },
  {
    code_v1: 98,
    firstPage: 128,
    id: 6,
    lastPage: 150,
    revelationPlace: 'makkah',
    slug: 'al-anam',
    translatedName: 'الأنعام',
    transliteratedName: 'الأنعام',
    type: 'chapter',
    versesCount: 165,
  },
  {
    code_v1: 99,
    firstPage: 151,
    id: 7,
    lastPage: 176,
    revelationPlace: 'makkah',
    slug: 'al-araf',
    translatedName: 'الأعراف',
    transliteratedName: 'الأعراف',
    type: 'chapter',
    versesCount: 206,
  },
  {
    code_v1: 100,
    firstPage: 177,
    id: 8,
    lastPage: 186,
    revelationPlace: 'madinah',
    slug: 'al-anfal',
    translatedName: 'الأنفال',
    transliteratedName: 'الأنفال',
    type: 'chapter',
    versesCount: 75,
  },
  {
    code_v1: 101,
    firstPage: 187,
    hasBasmalah: false,
    id: 9,
    lastPage: 207,
    revelationPlace: 'madinah',
    slug: 'at-tawbah',
    translatedName: 'التوبة',
    transliteratedName: 'التوبة',
    type: 'chapter',
    versesCount: 129,
  },
  {
    code_v1: 102,
    firstPage: 208,
    id: 10,
    lastPage: 221,
    revelationPlace: 'makkah',
    slug: 'yunus',
    translatedName: 'يونس',
    transliteratedName: 'يونس',
    type: 'chapter',
    versesCount: 109,
  },
  {
    code_v1: 103,
    firstPage: 221,
    id: 11,
    lastPage: 235,
    revelationPlace: 'makkah',
    slug: 'hud',
    translatedName: 'هود',
    transliteratedName: 'هود',
    type: 'chapter',
    versesCount: 123,
  },
  {
    code_v1: 104,
    firstPage: 235,
    id: 12,
    lastPage: 248,
    revelationPlace: 'makkah',
    slug: 'yusuf',
    translatedName: 'يوسف',
    transliteratedName: 'يوسف',
    type: 'chapter',
    versesCount: 111,
  },
  {
    code_v1: 105,
    firstPage: 249,
    id: 13,
    lastPage: 255,
    revelationPlace: 'madinah',
    slug: 'ar-rad',
    translatedName: 'الرعد',
    transliteratedName: 'الرعد',
    type: 'chapter',
    versesCount: 43,
  },
  {
    code_v1: 106,
    firstPage: 255,
    id: 14,
    lastPage: 261,
    revelationPlace: 'makkah',
    slug: 'ibrahim',
    translatedName: 'ابراهيم',
    transliteratedName: 'ابراهيم',
    type: 'chapter',
    versesCount: 52,
  },
  {
    code_v1: 107,
    firstPage: 262,
    id: 15,
    lastPage: 267,
    revelationPlace: 'makkah',
    slug: 'al-hijr',
    translatedName: 'الحجر',
    transliteratedName: 'الحجر',
    type: 'chapter',
    versesCount: 99,
  },
  {
    code_v1: 108,
    firstPage: 267,
    id: 16,
    lastPage: 281,
    revelationPlace: 'makkah',
    slug: 'an-nahl',
    translatedName: 'النحل',
    transliteratedName: 'النحل',
    type: 'chapter',
    versesCount: 128,
  },
  {
    code_v1: 109,
    firstPage: 282,
    id: 17,
    lastPage: 293,
    revelationPlace: 'makkah',
    slug: 'al-isra',
    translatedName: 'الإسراء',
    transliteratedName: 'الإسراء',
    type: 'chapter',
    versesCount: 111,
  },
  {
    code_v1: 110,
    firstPage: 293,
    id: 18,
    lastPage: 304,
    revelationPlace: 'makkah',
    slug: 'al-kahf',
    translatedName: 'الكهف',
    transliteratedName: 'الكهف',
    type: 'chapter',
    versesCount: 110,
  },
  {
    code_v1: 111,
    firstPage: 305,
    id: 19,
    lastPage: 312,
    revelationPlace: 'makkah',
    slug: 'maryam',
    translatedName: 'مريم',
    transliteratedName: 'مريم',
    type: 'chapter',
    versesCount: 98,
  },
  {
    code_v1: 112,
    firstPage: 312,
    id: 20,
    lastPage: 321,
    revelationPlace: 'makkah',
    slug: 'taha',
    translatedName: 'طه',
    transliteratedName: 'طه',
    type: 'chapter',
    versesCount: 135,
  },
  {
    code_v1: 113,
    firstPage: 322,
    id: 21,
    lastPage: 331,
    revelationPlace: 'makkah',
    slug: 'al-anbya',
    translatedName: 'الأنبياء',
    transliteratedName: 'الأنبياء',
    type: 'chapter',
    versesCount: 112,
  },
  {
    code_v1: 114,
    firstPage: 334,
    id: 22,
    lastPage: 341,
    revelationPlace: 'madinah',
    slug: 'al-hajj',
    translatedName: 'الحج',
    transliteratedName: 'الحج',
    type: 'chapter',
    versesCount: 78,
  },
  {
    code_v1: 115,
    firstPage: 342,
    id: 23,
    lastPage: 349,
    revelationPlace: 'makkah',
    slug: 'al-muminun',
    translatedName: 'المؤمنون',
    transliteratedName: 'المؤمنون',
    type: 'chapter',
    versesCount: 118,
  },
  {
    code_v1: 116,
    firstPage: 350,
    id: 24,
    lastPage: 359,
    revelationPlace: 'madinah',
    slug: 'an-nur',
    translatedName: 'النور',
    transliteratedName: 'النور',
    type: 'chapter',
    versesCount: 64,
  },
  {
    code_v1: 117,
    firstPage: 359,
    id: 25,
    lastPage: 366,
    revelationPlace: 'makkah',
    slug: 'al-furqan',
    translatedName: 'الفرقان',
    transliteratedName: 'الفرقان',
    type: 'chapter',
    versesCount: 77,
  },
  {
    code_v1: 118,
    firstPage: 367,
    id: 26,
    lastPage: 376,
    revelationPlace: 'makkah',
    slug: 'ash-shuara',
    translatedName: 'الشعراء',
    transliteratedName: 'الشعراء',
    type: 'chapter',
    versesCount: 227,
  },
  {
    code_v1: 119,
    firstPage: 377,
    id: 27,
    lastPage: 385,
    revelationPlace: 'makkah',
    slug: 'an-naml',
    translatedName: 'النمل',
    transliteratedName: 'النمل',
    type: 'chapter',
    versesCount: 93,
  },
  {
    code_v1: 120,
    firstPage: 385,
    id: 28,
    lastPage: 396,
    revelationPlace: 'makkah',
    slug: 'al-qasas',
    translatedName: 'القصص',
    transliteratedName: 'القصص',
    type: 'chapter',
    versesCount: 88,
  },
  {
    code_v1: 121,
    firstPage: 396,
    id: 29,
    lastPage: 404,
    revelationPlace: 'makkah',
    slug: 'al-ankabut',
    translatedName: 'العنكبوت',
    transliteratedName: 'العنكبوت',
    type: 'chapter',
    versesCount: 69,
  },
  {
    code_v1: 122,
    firstPage: 404,
    id: 30,
    lastPage: 410,
    revelationPlace: 'makkah',
    slug: 'ar-rum',
    translatedName: 'الروم',
    transliteratedName: 'الروم',
    type: 'chapter',
    versesCount: 60,
  },
  {
    code_v1: 125,
    firstPage: 411,
    id: 31,
    lastPage: 414,
    revelationPlace: 'makkah',
    slug: 'luqman',
    translatedName: 'لقمان',
    transliteratedName: 'لقمان',
    type: 'chapter',
    versesCount: 34,
  },
  {
    code_v1: 124,
    firstPage: 415,
    id: 32,
    lastPage: 417,
    revelationPlace: 'makkah',
    slug: 'as-sajdah',
    translatedName: 'السجدة',
    transliteratedName: 'السجدة',
    type: 'chapter',
    versesCount: 30,
  },
  {
    code_v1: 123,
    firstPage: 418,
    id: 33,
    lastPage: 427,
    revelationPlace: 'madinah',
    slug: 'al-ahzab',
    translatedName: 'الأحزاب',
    transliteratedName: 'الأحزاب',
    type: 'chapter',
    versesCount: 73,
  },
  {
    code_v1: 126,
    firstPage: 428,
    id: 34,
    lastPage: 434,
    revelationPlace: 'makkah',
    slug: 'saba',
    translatedName: 'سبإ',
    transliteratedName: 'سبإ',
    type: 'chapter',
    versesCount: 54,
  },
  {
    code_v1: 127,
    firstPage: 434,
    id: 35,
    lastPage: 440,
    revelationPlace: 'makkah',
    slug: 'fatir',
    translatedName: 'فاطر',
    transliteratedName: 'فاطر',
    type: 'chapter',
    versesCount: 45,
  },
  {
    code_v1: 161,
    firstPage: 440,
    id: 36,
    lastPage: 445,
    revelationPlace: 'makkah',
    slug: 'ya-sin',
    translatedName: 'يس',
    transliteratedName: 'يس',
    type: 'chapter',
    versesCount: 83,
  },
  {
    code_v1: 162,
    firstPage: 446,
    id: 37,
    lastPage: 452,
    revelationPlace: 'makkah',
    slug: 'as-saffat',
    translatedName: 'الصافات',
    transliteratedName: 'الصافات',
    type: 'chapter',
    versesCount: 182,
  },
  {
    code_v1: 163,
    firstPage: 453,
    id: 38,
    lastPage: 458,
    revelationPlace: 'makkah',
    slug: 'sad',
    translatedName: 'ص',
    transliteratedName: 'ص',
    type: 'chapter',
    versesCount: 88,
  },
  {
    code_v1: 164,
    firstPage: 458,
    id: 39,
    lastPage: 467,
    revelationPlace: 'makkah',
    slug: 'az-zumar',
    translatedName: 'الزمر',
    transliteratedName: 'الزمر',
    type: 'chapter',
    versesCount: 75,
  },
  {
    code_v1: 165,
    firstPage: 467,
    id: 40,
    lastPage: 476,
    revelationPlace: 'makkah',
    slug: 'ghafir',
    translatedName: 'غافر',
    transliteratedName: 'غافر',
    type: 'chapter',
    versesCount: 85,
  },
  {
    code_v1: 166,
    firstPage: 477,
    id: 41,
    lastPage: 482,
    revelationPlace: 'makkah',
    slug: 'fussilat',
    translatedName: 'فصلت',
    transliteratedName: 'فصلت',
    type: 'chapter',
    versesCount: 54,
  },
  {
    code_v1: 167,
    firstPage: 483,
    id: 42,
    lastPage: 488,
    revelationPlace: 'makkah',
    slug: 'ash-shuraa',
    translatedName: 'الشورى',
    transliteratedName: 'الشورى',
    type: 'chapter',
    versesCount: 53,
  },
  {
    code_v1: 168,
    firstPage: 488,
    id: 43,
    lastPage: 495,
    revelationPlace: 'makkah',
    slug: 'az-zukhruf',
    translatedName: 'الزخرف',
    transliteratedName: 'الزخرف',
    type: 'chapter',
    versesCount: 89,
  },
  {
    code_v1: 169,
    firstPage: 496,
    id: 44,
    lastPage: 498,
    revelationPlace: 'makkah',
    slug: 'ad-dukhan',
    translatedName: 'الدخان',
    transliteratedName: 'الدخان',
    type: 'chapter',
    versesCount: 59,
  },
  {
    code_v1: 170,
    firstPage: 499,
    id: 45,
    lastPage: 502,
    revelationPlace: 'makkah',
    slug: 'al-jathiyah',
    translatedName: 'الجاثية',
    transliteratedName: 'الجاثية',
    type: 'chapter',
    versesCount: 37,
  },
  {
    code_v1: 187,
    firstPage: 502,
    id: 46,
    lastPage: 506,
    revelationPlace: 'makkah',
    slug: 'al-ahqaf',
    translatedName: 'الأحقاف',
    transliteratedName: 'الأحقاف',
    type: 'chapter',
    versesCount: 35,
  },
  {
    code_v1: 172,
    firstPage: 507,
    id: 47,
    lastPage: 510,
    revelationPlace: 'madinah',
    slug: 'muhammad',
    translatedName: 'محمد',
    transliteratedName: 'محمد',
    type: 'chapter',
    versesCount: 38,
  },
  {
    code_v1: 174,
    firstPage: 511,
    id: 48,
    lastPage: 515,
    revelationPlace: 'madinah',
    slug: 'al-fath',
    translatedName: 'الفتح',
    transliteratedName: 'الفتح',
    type: 'chapter',
    versesCount: 29,
  },
  {
    code_v1: 175,
    firstPage: 515,
    id: 49,
    lastPage: 517,
    revelationPlace: 'madinah',
    slug: 'al-hujurat',
    translatedName: 'الحجرات',
    transliteratedName: 'الحجرات',
    type: 'chapter',
    versesCount: 18,
  },
  {
    code_v1: 176,
    firstPage: 518,
    id: 50,
    lastPage: 520,
    revelationPlace: 'makkah',
    slug: 'qaf',
    translatedName: 'ق',
    transliteratedName: 'ق',
    type: 'chapter',
    versesCount: 45,
  },
  {
    code_v1: 177,
    firstPage: 520,
    id: 51,
    lastPage: 523,
    revelationPlace: 'makkah',
    slug: 'adh-dhariyat',
    translatedName: 'الذاريات',
    transliteratedName: 'الذاريات',
    type: 'chapter',
    versesCount: 60,
  },
  {
    code_v1: 178,
    firstPage: 523,
    id: 52,
    lastPage: 525,
    revelationPlace: 'makkah',
    slug: 'at-tur',
    translatedName: 'الطور',
    transliteratedName: 'الطور',
    type: 'chapter',
    versesCount: 49,
  },
  {
    code_v1: 179,
    firstPage: 526,
    id: 53,
    lastPage: 528,
    revelationPlace: 'makkah',
    slug: 'an-najm',
    translatedName: 'النجم',
    transliteratedName: 'النجم',
    type: 'chapter',
    versesCount: 62,
  },
  {
    code_v1: 180,
    firstPage: 528,
    id: 54,
    lastPage: 531,
    revelationPlace: 'makkah',
    slug: 'al-qamar',
    translatedName: 'القمر',
    transliteratedName: 'القمر',
    type: 'chapter',
    versesCount: 55,
  },
  {
    code_v1: 181,
    firstPage: 531,
    id: 55,
    lastPage: 534,
    revelationPlace: 'madinah',
    slug: 'ar-rahman',
    translatedName: 'الرحمن',
    transliteratedName: 'الرحمن',
    type: 'chapter',
    versesCount: 78,
  },
  {
    code_v1: 182,
    firstPage: 534,
    id: 56,
    lastPage: 537,
    revelationPlace: 'makkah',
    slug: 'al-waqiah',
    translatedName: 'الواقعة',
    transliteratedName: 'الواقعة',
    type: 'chapter',
    versesCount: 96,
  },
  {
    code_v1: 184,
    firstPage: 537,
    id: 57,
    lastPage: 541,
    revelationPlace: 'madinah',
    slug: 'al-hadid',
    translatedName: 'الحديد',
    transliteratedName: 'الحديد',
    type: 'chapter',
    versesCount: 29,
  },
  {
    code_v1: 185,
    firstPage: 542,
    id: 58,
    lastPage: 545,
    revelationPlace: 'madinah',
    slug: 'al-mujadila',
    translatedName: 'المجادلة',
    transliteratedName: 'المجادلة',
    type: 'chapter',
    versesCount: 22,
  },
  {
    code_v1: 186,
    firstPage: 545,
    id: 59,
    lastPage: 548,
    revelationPlace: 'madinah',
    slug: 'al-hashr',
    translatedName: 'الحشر',
    transliteratedName: 'الحشر',
    type: 'chapter',
    versesCount: 24,
  },
  {
    code_v1: 171,
    firstPage: 549,
    id: 60,
    lastPage: 551,
    revelationPlace: 'madinah',
    slug: 'al-mumtahanah',
    translatedName: 'الممتحنة',
    transliteratedName: 'الممتحنة',
    type: 'chapter',
    versesCount: 13,
  },
  {
    code_v1: 188,
    firstPage: 551,
    id: 61,
    lastPage: 552,
    revelationPlace: 'madinah',
    slug: 'as-saf',
    translatedName: 'الصف',
    transliteratedName: 'الصف',
    type: 'chapter',
    versesCount: 14,
  },
  {
    code_v1: 189,
    firstPage: 553,
    id: 62,
    lastPage: 554,
    revelationPlace: 'madinah',
    slug: 'al-jumuah',
    translatedName: 'الجمعة',
    transliteratedName: 'الجمعة',
    type: 'chapter',
    versesCount: 11,
  },
  {
    code_v1: 190,
    firstPage: 554,
    id: 63,
    lastPage: 555,
    revelationPlace: 'madinah',
    slug: 'al-munafiqun',
    translatedName: 'المنافقون',
    transliteratedName: 'المنافقون',
    type: 'chapter',
    versesCount: 11,
  },
  {
    code_v1: 191,
    firstPage: 556,
    id: 64,
    lastPage: 557,
    revelationPlace: 'madinah',
    slug: 'at-taghabun',
    translatedName: 'التغابن',
    transliteratedName: 'التغابن',
    type: 'chapter',
    versesCount: 18,
  },
  {
    code_v1: 192,
    firstPage: 558,
    id: 65,
    lastPage: 559,
    revelationPlace: 'madinah',
    slug: 'at-talaq',
    translatedName: 'الطلاق',
    transliteratedName: 'الطلاق',
    type: 'chapter',
    versesCount: 12,
  },
  {
    code_v1: 193,
    firstPage: 560,
    id: 66,
    lastPage: 561,
    revelationPlace: 'madinah',
    slug: 'at-tahrim',
    translatedName: 'التحريم',
    transliteratedName: 'التحريم',
    type: 'chapter',
    versesCount: 12,
  },
  {
    code_v1: 194,
    firstPage: 562,
    id: 67,
    lastPage: 564,
    revelationPlace: 'makkah',
    slug: 'al-mulk',
    translatedName: 'الملك',
    transliteratedName: 'الملك',
    type: 'chapter',
    versesCount: 30,
  },
  {
    code_v1: 195,
    firstPage: 564,
    id: 68,
    lastPage: 566,
    revelationPlace: 'makkah',
    slug: 'al-qalam',
    translatedName: 'القلم',
    transliteratedName: 'القلم',
    type: 'chapter',
    versesCount: 52,
  },
  {
    code_v1: 196,
    firstPage: 566,
    id: 69,
    lastPage: 568,
    revelationPlace: 'makkah',
    slug: 'al-haqqah',
    translatedName: 'الحاقة',
    transliteratedName: 'الحاقة',
    type: 'chapter',
    versesCount: 52,
  },
  {
    code_v1: 197,
    firstPage: 568,
    id: 70,
    lastPage: 570,
    revelationPlace: 'makkah',
    slug: 'al-maarij',
    translatedName: 'المعارج',
    transliteratedName: 'المعارج',
    type: 'chapter',
    versesCount: 44,
  },
  {
    code_v1: 198,
    firstPage: 570,
    id: 71,
    lastPage: 571,
    revelationPlace: 'makkah',
    slug: 'nuh',
    translatedName: 'نوح',
    transliteratedName: 'نوح',
    type: 'chapter',
    versesCount: 28,
  },
  {
    code_v1: 199,
    firstPage: 572,
    id: 72,
    lastPage: 573,
    revelationPlace: 'makkah',
    slug: 'al-jinn',
    translatedName: 'الجن',
    transliteratedName: 'الجن',
    type: 'chapter',
    versesCount: 28,
  },
  {
    code_v1: 200,
    firstPage: 574,
    id: 73,
    lastPage: 575,
    revelationPlace: 'makkah',
    slug: 'al-muzzammil',
    translatedName: 'المزمل',
    transliteratedName: 'المزمل',
    type: 'chapter',
    versesCount: 20,
  },
  {
    code_v1: 201,
    firstPage: 575,
    id: 74,
    lastPage: 577,
    revelationPlace: 'makkah',
    slug: 'al-muddaththir',
    translatedName: 'المدثر',
    transliteratedName: 'المدثر',
    type: 'chapter',
    versesCount: 56,
  },
  {
    code_v1: 202,
    firstPage: 577,
    id: 75,
    lastPage: 578,
    revelationPlace: 'makkah',
    slug: 'al-qiyamah',
    translatedName: 'القيامة',
    transliteratedName: 'القيامة',
    type: 'chapter',
    versesCount: 40,
  },
  {
    code_v1: 203,
    firstPage: 578,
    id: 76,
    lastPage: 580,
    revelationPlace: 'madinah',
    slug: 'al-insan',
    translatedName: 'الانسان',
    transliteratedName: 'الانسان',
    type: 'chapter',
    versesCount: 31,
  },
  {
    code_v1: 204,
    firstPage: 580,
    id: 77,
    lastPage: 581,
    revelationPlace: 'makkah',
    slug: 'al-mursalat',
    translatedName: 'المرسلات',
    transliteratedName: 'المرسلات',
    type: 'chapter',
    versesCount: 50,
  },
  {
    code_v1: 205,
    firstPage: 582,
    id: 78,
    lastPage: 583,
    revelationPlace: 'makkah',
    slug: 'an-naba',
    translatedName: 'النبإ',
    transliteratedName: 'النبإ',
    type: 'chapter',
    versesCount: 40,
  },
  {
    code_v1: 206,
    firstPage: 583,
    id: 79,
    lastPage: 584,
    revelationPlace: 'makkah',
    slug: 'an-naziat',
    translatedName: 'النازعات',
    transliteratedName: 'النازعات',
    type: 'chapter',
    versesCount: 46,
  },
  {
    code_v1: 207,
    firstPage: 585,
    id: 80,
    revelationPlace: 'makkah',
    slug: 'abasa',
    translatedName: 'عبس',
    transliteratedName: 'عبس',
    type: 'chapter',
    versesCount: 42,
  },
  {
    code_v1: 208,
    firstPage: 586,
    id: 81,
    revelationPlace: 'makkah',
    slug: 'at-takwir',
    translatedName: 'التكوير',
    transliteratedName: 'التكوير',
    type: 'chapter',
    versesCount: 29,
  },
  {
    code_v1: 209,
    firstPage: 587,
    id: 82,
    revelationPlace: 'makkah',
    slug: 'al-infitar',
    translatedName: 'الإنفطار',
    transliteratedName: 'الإنفطار',
    type: 'chapter',
    versesCount: 19,
  },
  {
    code_v1: 210,
    firstPage: 587,
    id: 83,
    lastPage: 589,
    revelationPlace: 'makkah',
    slug: 'al-mutaffifin',
    translatedName: 'المطففين',
    transliteratedName: 'المطففين',
    type: 'chapter',
    versesCount: 36,
  },
  {
    code_v1: 211,
    firstPage: 589,
    id: 84,
    revelationPlace: 'makkah',
    slug: 'al-inshiqaq',
    translatedName: 'الإنشقاق',
    transliteratedName: 'الإنشقاق',
    type: 'chapter',
    versesCount: 25,
  },
  {
    code_v1: 212,
    firstPage: 590,
    id: 85,
    revelationPlace: 'makkah',
    slug: 'al-buruj',
    translatedName: 'البروج',
    transliteratedName: 'البروج',
    type: 'chapter',
    versesCount: 22,
  },
  {
    code_v1: 213,
    firstPage: 591,
    id: 86,
    revelationPlace: 'makkah',
    slug: 'at-tariq',
    translatedName: 'الطارق',
    transliteratedName: 'الطارق',
    type: 'chapter',
    versesCount: 17,
  },
  {
    code_v1: 214,
    firstPage: 591,
    id: 87,
    lastPage: 592,
    revelationPlace: 'makkah',
    slug: 'al-ala',
    translatedName: 'الأعلى',
    transliteratedName: 'الأعلى',
    type: 'chapter',
    versesCount: 19,
  },
  {
    code_v1: 215,
    firstPage: 592,
    id: 88,
    revelationPlace: 'makkah',
    slug: 'al-ghashiyah',
    translatedName: 'الغاشية',
    transliteratedName: 'الغاشية',
    type: 'chapter',
    versesCount: 26,
  },
  {
    code_v1: 216,
    firstPage: 593,
    id: 89,
    lastPage: 594,
    revelationPlace: 'makkah',
    slug: 'al-fajr',
    translatedName: 'الفجر',
    transliteratedName: 'الفجر',
    type: 'chapter',
    versesCount: 30,
  },
  {
    code_v1: 217,
    firstPage: 594,
    id: 90,
    revelationPlace: 'makkah',
    slug: 'al-balad',
    translatedName: 'البلد',
    transliteratedName: 'البلد',
    type: 'chapter',
    versesCount: 20,
  },
  {
    code_v1: 218,
    firstPage: 595,
    id: 91,
    revelationPlace: 'makkah',
    slug: 'ash-shams',
    translatedName: 'الشمس',
    transliteratedName: 'الشمس',
    type: 'chapter',
    versesCount: 15,
  },
  {
    code_v1: 219,
    firstPage: 595,
    id: 92,
    lastPage: 596,
    revelationPlace: 'makkah',
    slug: 'al-layl',
    translatedName: 'الليل',
    transliteratedName: 'الليل',
    type: 'chapter',
    versesCount: 21,
  },
  {
    code_v1: 220,
    firstPage: 596,
    id: 93,
    revelationPlace: 'makkah',
    slug: 'ad-duhaa',
    translatedName: 'الضحى',
    transliteratedName: 'الضحى',
    type: 'chapter',
    versesCount: 11,
  },
  {
    code_v1: 221,
    firstPage: 596,
    id: 94,
    revelationPlace: 'makkah',
    slug: 'ash-sharh',
    translatedName: 'الشرح',
    transliteratedName: 'الشرح',
    type: 'chapter',
    versesCount: 8,
  },
  {
    code_v1: 222,
    firstPage: 597,
    id: 95,
    revelationPlace: 'makkah',
    slug: 'at-tin',
    translatedName: 'التين',
    transliteratedName: 'التين',
    type: 'chapter',
    versesCount: 8,
  },
  {
    code_v1: 223,
    firstPage: 597,
    id: 96,
    revelationPlace: 'makkah',
    slug: 'al-alaq',
    translatedName: 'العلق',
    transliteratedName: 'العلق',
    type: 'chapter',
    versesCount: 19,
  },
  {
    code_v1: 224,
    firstPage: 598,
    id: 97,
    revelationPlace: 'makkah',
    slug: 'al-qadr',
    translatedName: 'القدر',
    transliteratedName: 'القدر',
    type: 'chapter',
    versesCount: 5,
  },
  {
    code_v1: 225,
    firstPage: 598,
    id: 98,
    lastPage: 599,
    revelationPlace: 'madinah',
    slug: 'al-bayyinah',
    translatedName: 'البينة',
    transliteratedName: 'البينة',
    type: 'chapter',
    versesCount: 8,
  },
  {
    code_v1: 226,
    firstPage: 599,
    id: 99,
    revelationPlace: 'madinah',
    slug: 'az-zalzalah',
    translatedName: 'الزلزلة',
    transliteratedName: 'الزلزلة',
    type: 'chapter',
    versesCount: 8,
  },
  {
    code_v1: 227,
    firstPage: 599,
    id: 100,
    lastPage: 600,
    revelationPlace: 'makkah',
    slug: 'al-adiyat',
    translatedName: 'العاديات',
    transliteratedName: 'العاديات',
    type: 'chapter',
    versesCount: 11,
  },
  {
    code_v1: 228,
    firstPage: 600,
    id: 101,
    revelationPlace: 'makkah',
    slug: 'al-qariah',
    translatedName: 'القارعة',
    transliteratedName: 'القارعة',
    type: 'chapter',
    versesCount: 11,
  },
  {
    code_v1: 229,
    firstPage: 600,
    id: 102,
    revelationPlace: 'makkah',
    slug: 'at-takathur',
    translatedName: 'التكاثر',
    transliteratedName: 'التكاثر',
    type: 'chapter',
    versesCount: 8,
  },
  {
    code_v1: 230,
    firstPage: 601,
    id: 103,
    revelationPlace: 'makkah',
    slug: 'al-asr',
    translatedName: 'العصر',
    transliteratedName: 'العصر',
    type: 'chapter',
    versesCount: 3,
  },
  {
    code_v1: 231,
    firstPage: 601,
    id: 104,
    revelationPlace: 'makkah',
    slug: 'al-humazah',
    translatedName: 'الهمزة',
    transliteratedName: 'الهمزة',
    type: 'chapter',
    versesCount: 9,
  },
  {
    code_v1: 232,
    firstPage: 601,
    id: 105,
    revelationPlace: 'makkah',
    slug: 'al-fil',
    translatedName: 'الفيل',
    transliteratedName: 'الفيل',
    type: 'chapter',
    versesCount: 5,
  },
  {
    code_v1: 233,
    firstPage: 602,
    id: 106,
    revelationPlace: 'makkah',
    slug: 'quraysh',
    translatedName: 'قريش',
    transliteratedName: 'قريش',
    type: 'chapter',
    versesCount: 4,
  },
  {
    code_v1: 234,
    firstPage: 602,
    id: 107,
    revelationPlace: 'makkah',
    slug: 'al-maun',
    translatedName: 'الماعون',
    transliteratedName: 'الماعون',
    type: 'chapter',
    versesCount: 7,
  },
  {
    code_v1: 235,
    firstPage: 602,
    id: 108,
    revelationPlace: 'makkah',
    slug: 'al-kawthar',
    translatedName: 'الكوثر',
    transliteratedName: 'الكوثر',
    type: 'chapter',
    versesCount: 3,
  },
  {
    code_v1: 236,
    firstPage: 603,
    id: 109,
    revelationPlace: 'makkah',
    slug: 'al-kafirun',
    translatedName: 'الكافرون',
    transliteratedName: 'الكافرون',
    type: 'chapter',
    versesCount: 6,
  },
  {
    code_v1: 237,
    firstPage: 603,
    id: 110,
    revelationPlace: 'madinah',
    slug: 'an-nasr',
    translatedName: 'النصر',
    transliteratedName: 'النصر',
    type: 'chapter',
    versesCount: 3,
  },
  {
    code_v1: 238,
    firstPage: 603,
    id: 111,
    revelationPlace: 'makkah',
    slug: 'al-masad',
    translatedName: 'المسد',
    transliteratedName: 'المسد',
    type: 'chapter',
    versesCount: 5,
  },
  {
    code_v1: 239,
    firstPage: 604,
    id: 112,
    revelationPlace: 'makkah',
    slug: 'al-ikhlas',
    translatedName: 'الإخلاص',
    transliteratedName: 'الإخلاص',
    type: 'chapter',
    versesCount: 4,
  },
  {
    code_v1: 240,
    firstPage: 604,
    id: 113,
    revelationPlace: 'makkah',
    slug: 'al-falaq',
    translatedName: 'الفلق',
    transliteratedName: 'الفلق',
    type: 'chapter',
    versesCount: 5,
  },
  {
    code_v1: 241,
    firstPage: 604,
    id: 114,
    revelationPlace: 'makkah',
    slug: 'an-nas',
    translatedName: 'الناس',
    transliteratedName: 'الناس',
    type: 'chapter',
    versesCount: 6,
  },
];
export default QuranChapters;
